/**
 * DEMO DATA — fictional company names and addresses used in mock/demo mode only.
 * In real mode (SUI_CLIENT=real), party details come from on-chain objects and user input.
 * Aligned with test/Scenario_C_memwal_baseline PDFs; generated by scripts/generate-memory-demo-docs.ts.
 */

export const SCENARIO_C_IMPORTER = {
  company: "Shanghai Smart Imports Co Ltd",
  contact: "Wei Zhang",
  email: "wei.zhang@shanghaismartimports.cn",
  phone: "+86-21-555-0100",
  country: "China",
  taxId: "CN-987654321",
  registeredAddress: "88 Pudong Avenue, Shanghai, China",
};

export const SCENARIO_C_FREIGHT_FORWARDER = {
  company: "Freight Forwarder",
  contact: "Logistics Desk",
  email: "ops@freightforwarder.com",
  phone: "+1-310-555-0300",
  country: "United States",
  taxId: "US-FF-900001",
  registeredAddress: "500 Harbor Logistics Park, Los Angeles, CA 90021, United States",
  bankBeneficiaryName: "Freight Forwarder",
  bankAccountNumber: "FF-SETTLE-4401",
};

export const SCENARIO_C_EXPORTER = {
  company: "Acme Robotics LLC",
  contact: "Sarah Chen",
  email: "sarah.chen@acmerobotics.com",
  phone: "+1-310-555-0200",
  country: "United States",
  taxId: "US-123456789",
  registeredAddress: "123 Harbor Way, Los Angeles, CA 90012, United States",
  bankBeneficiaryName: "Acme Robotics LLC",
  bankAccountNumber: "BANK REF ABC-8842",
};

export const SCENARIO_C_SHIPMENT_DETAILS = {
  origin: "Los Angeles, CA",
  originPort: "Los Angeles, CA",
  destination: "Shanghai, China",
  destinationPort: "Shanghai, China",
  carrier: "Pacific Star Lines",
  transportMode: "Sea",
  incoterm: "FOB",
  etd: "2026-05-21",
  eta: "2026-05-22",
  declaredValue: "50000",
  currency: "USD",
  bookingRef: "BL-MEM-001",
  paymentTerms: "BANK REF ABC-8842",
  blType: "House",
};

export const SCENARIO_C_CARGO = {
  description: "Industrial tablet computers",
  sku: "TAB-8471",
  hsCode: "8471.30",
  quantity: "100",
  grossWeight: "1200 kg",
  netWeight: "1000 kg",
  handlingUnits: "100 Cartons",
  container: "",
  seal: "",
  countryOfOrigin: "United States",
  dangerousGoods: "No",
  temperatureControlled: "No",
};

export type DemoPartyDetails = {
  company: string;
  contact: string;
  email: string;
  phone: string;
  taxId: string;
  registeredAddress?: string;
  bankBeneficiaryName?: string;
  bankAccountNumber?: string;
};

export const SCENARIO_C_IMPORTER_PARTY: DemoPartyDetails = { ...SCENARIO_C_IMPORTER };
export const SCENARIO_C_EXPORTER_PARTY: DemoPartyDetails = { ...SCENARIO_C_EXPORTER };
export const SCENARIO_C_FREIGHT_FORWARDER_PARTY: DemoPartyDetails = { ...SCENARIO_C_FREIGHT_FORWARDER };

function normalizeCompanyKey(name: string): string {
  return name.trim().toLowerCase().replace(/[^a-z0-9]+/g, " ");
}

const COMPANY_PARTY_CATALOG: Record<string, DemoPartyDetails> = {
  [normalizeCompanyKey(SCENARIO_C_EXPORTER.company)]: SCENARIO_C_EXPORTER_PARTY,
  [normalizeCompanyKey(SCENARIO_C_IMPORTER.company)]: SCENARIO_C_IMPORTER_PARTY,
  [normalizeCompanyKey(SCENARIO_C_FREIGHT_FORWARDER.company)]: SCENARIO_C_FREIGHT_FORWARDER_PARTY,
};

/** Look up canonical tax ID, address, and bank fields for a known demo company name. */
export function lookupCompanyPartyDetails(companyName: string): DemoPartyDetails | null {
  const key = normalizeCompanyKey(companyName);
  if (COMPANY_PARTY_CATALOG[key]) return COMPANY_PARTY_CATALOG[key];
  if (key.includes("acme")) return SCENARIO_C_EXPORTER_PARTY;
  if (key.includes("shanghai smart")) return SCENARIO_C_IMPORTER_PARTY;
  return null;
}

/** Apply registered identity fields (tax ID, address, bank) for known companies; keep contact overrides. */
export function enrichPartyWithCompanyCatalog<T extends DemoPartyDetails>(party: T): T {
  const known = lookupCompanyPartyDetails(party.company);
  if (!known) return party;
  return {
    ...party,
    company: party.company.trim() || known.company,
    contact: party.contact || known.contact,
    email: party.email || known.email,
    phone: party.phone || known.phone,
    taxId: known.taxId,
    registeredAddress: known.registeredAddress,
    bankBeneficiaryName: known.bankBeneficiaryName,
    bankAccountNumber: known.bankAccountNumber,
  };
}
